spring:
  application:
      name: sptingboot-mybatis-demo
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
